import { useState } from 'react';
import { ArrowUpRight, Github } from 'lucide-react';

/**
 * GitHub activity visualisations.
 *
 * Embeds three SVG views generated by vercel-hosted services
 * (no API keys, no rate limiting concerns, no maintenance):
 *
 *  1. Activity graph (line/area chart of commit counts over the year)
 *  2. Stats card (totals, stars, top languages)
 *  3. Streak card (current + longest commit streak)
 *
 * Each SVG is themed to match the portfolio palette via URL params.
 * The graphs auto-update — no rebuild needed when you push new commits.
 */

const GITHUB_USERNAME = 'vsvidhun06-blip';

// Theme params — keep in sync with tailwind palette
const BG = '050816';
const TITLE = '3B82F6';
const ICON = '8B5CF6';
const TEXT = 'E5E7EB';
const BORDER = '1E293B';
const LINE = '3B82F6';
const POINT = '8B5CF6';

// Activity-graph (Vercel-hosted, reliable)
const ACTIVITY_GRAPH = `https://github-readme-activity-graph.vercel.app/graph?username=${GITHUB_USERNAME}&bg_color=${BG}&color=${TEXT}&line=${LINE}&point=${POINT}&area=true&area_color=${LINE}&hide_border=true&custom_title=commit%20activity%20%E2%80%94%20last%2031%20days&radius=8`;

// Stats card
const STATS_CARD = `https://github-readme-stats.vercel.app/api?username=${GITHUB_USERNAME}&show_icons=true&hide_border=true&bg_color=${BG}&title_color=${TITLE}&text_color=${TEXT}&icon_color=${ICON}&hide_rank=false&include_all_commits=true&count_private=true`;

// Streak card
const STREAK_CARD = `https://github-readme-streak-stats.herokuapp.com/?user=${GITHUB_USERNAME}&theme=transparent&hide_border=true&background=${BG}&stroke=${BORDER}&ring=${TITLE}&fire=${ICON}&currStreakLabel=${TITLE}&sideLabels=${TEXT}&currStreakNum=${TEXT}&sideNums=${TEXT}&dates=94A3B8`;

function GraphCard({ src, alt, height = 'auto' }) {
  const [loaded, setLoaded] = useState(false);
  const [errored, setErrored] = useState(false);

  if (errored) {
    return (
      <div className="rounded-lg border border-cream-100/10 bg-ink-800/40 p-6 text-center">
        <p className="font-mono text-xs text-cream-400">
          unable to load github activity — view directly at{' '}
          <a
            href={`https://github.com/${GITHUB_USERNAME}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-amber-400 hover:underline"
          >
            github.com/{GITHUB_USERNAME}
          </a>
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-lg overflow-hidden border border-cream-100/5 bg-ink-800/30 relative">
      {!loaded && (
        <div
          className="absolute inset-0 flex items-center justify-center"
          style={{ minHeight: 120 }}
        >
          <p className="font-mono text-[10px] text-cream-400 animate-pulse">
            loading {alt}...
          </p>
        </div>
      )}
      <img
        src={src}
        alt={alt}
        loading="lazy"
        onLoad={() => setLoaded(true)}
        onError={() => setErrored(true)}
        className="w-full block"
        style={{ height, opacity: loaded ? 1 : 0, transition: 'opacity 0.4s' }}
      />
    </div>
  );
}

export default function GitHubActivity() {
  return (
    <div className="space-y-4">
      {/* Activity graph (the wide one) */}
      <GraphCard src={ACTIVITY_GRAPH} alt="commit activity graph" />

      {/* Stats + streak side-by-side */}
      <div className="grid sm:grid-cols-2 gap-4">
        <GraphCard src={STATS_CARD} alt="github stats" />
        <GraphCard src={STREAK_CARD} alt="commit streak" />
      </div>

      {/* Footer link */}
      <a
        href={`https://github.com/${GITHUB_USERNAME}`}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-2 text-cream-300 hover:text-amber-400 transition-colors text-sm font-mono group"
      >
        <Github size={14} />
        github.com/{GITHUB_USERNAME}
        <ArrowUpRight
          size={12}
          className="group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform"
        />
      </a>
    </div>
  );
}
